services:
  mysql:
    image: mysql/mysql-server:8.0.47
    container_name: backend-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: UTC
    ports:
      - "3307:3306"
    command: >
      mysqld
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --innodb-file-per-table=ON
      --skip-host-cache=ON
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
